apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: chart
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go-plugin-multiarch/release.yaml@versionStream
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {}
        - name: jx-variables
          resources: {}
        - name: release-binary
          resources: {}
        - name: build-and-push-image
          resources: {}
        - name: chart-docs
          resources: {}
        - image: gcr.io/jenkinsxio/jx-boot:3.0.768
          name: release-chart
          resources: {}
          script: |
            #!/usr/bin/env sh
            if [ -d "/workspace/source/charts/$REPO_NAME" ]; then source .jx/variables.sh
            cd /workspace/source/charts/$REPO_NAME
            make release; else echo no charts; fi
        - image: gcr.io/jenkinsxio/jx-changelog:0.0.27
          name: changelog
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh

            if [ -d "charts/$REPO_NAME" ]; then
            sed -i -e "s/^version:.*/version: $VERSION/" ./charts/$REPO_NAME/Chart.yaml
            sed -i -e "s/repository:.*/repository: $DOCKER_REGISTRY\/$DOCKER_REGISTRY_ORG\/$APP_NAME/" ./charts/$REPO_NAME/values.yaml
            sed -i -e "s/tag:.*/tag: $VERSION/" ./charts/$REPO_NAME/values.yaml;
            else echo no charts; fi

            jx changelog create --verbose --header-file=hack/changelog-header.md --version=$VERSION --rev=$PULL_BASE_SHA --output-markdown=changelog.md --update-release=false

            git add * || true      
            git commit -a -m "chore: release $VERSION" --allow-empty
            git tag -fa v$VERSION -m "Release version $VERSION"
            git push origin v$VERSION
          resources: {}
        - name: upload-binaries
          image: goreleaser/goreleaser:v0.155.0
          env:
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: tekton-git
                key: password
          script: |
            #!/bin/bash
            source .jx/variables.sh
            #rm -rf templates
            echo "now running goreleaser"
            export BRANCH=$(git rev-parse --abbrev-ref HEAD)
            export BUILDDATE=$(date)
            export REV=$(git rev-parse HEAD)
            export GOVERSION="1.15"
            export ROOTPACKAGE="github.com/$REPO_OWNER/$REPO_NAME"
            goreleaser release
          resources: {}
        - name: multi-arch-images
          resources: {}
        - name: promote-release
          resources: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
